<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\Company;
use App\Models\Joblist;
use App\Models\Talent;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Company::factory()
        //     ->count(10)
        //     ->create();
            
        // Project::factory()
        //     ->count(10)
        //     ->create();
        
        // Joblist::factory()
        //     ->count(10)
        //     ->create();

        // Talent::factory()
        //     ->count(10)
        //     ->create();

        // Users
        DB::table('users')->insert([
            [
                'name' => 'Clyde Santiago',
                'email' => 'hello@clydesantiago.com',
                'password' => bcrypt('password'),
            ]
        ]);

        // Companies
        DB::table('companies')->insert([
            [
                'name' => 'San Miguel Corporation',
                'email' => 'info@sanmiguel.com',
                'website' => 'https://www.sanmiguel.com.ph',
            ],
            [
                'name' => 'SM Investments Corporation',
                'email' => 'info@sminvestments.com',
                'website' => 'https://www.sminvestments.com',
            ],
            [
                'name' => 'Ayala Corporation',
                'email' => 'info@ayala.com.ph',
                'website' => 'https://www.ayala.com.ph',
            ],
            [
                'name' => 'Jollibee Foods Corporation',
                'email' => 'info@jollibee.com.ph',
                'website' => 'https://www.jollibee.com.ph',
            ],
            [
                'name' => 'PLDT Inc.',
                'email' => 'info@pldt.com.ph',
                'website' => 'https://www.pldt.com.ph',
            ],
        ]);

        // Projects
        $projects = [
            [
                'company_id' => 1,
                'name' => 'ERP System Development',
                'description' => 'A comprehensive enterprise resource planning (ERP) system tailored for large corporations.',
                'short_description' => 'ERP system for large corporations',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 2,
                'name' => 'E-commerce Platform',
                'description' => 'Development of a robust e-commerce platform with multi-vendor support.',
                'short_description' => 'Multi-vendor e-commerce platform',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 3,
                'name' => 'CRM Software Development',
                'description' => 'A customer relationship management (CRM) software aimed at improving client engagement.',
                'short_description' => 'CRM software for client management',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 4,
                'name' => 'Inventory Management System',
                'description' => 'An inventory management system to streamline warehouse and supply chain operations.',
                'short_description' => 'Inventory management for supply chains',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 5,
                'name' => 'Mobile Banking Application',
                'description' => 'Development of a secure mobile banking application with advanced features.',
                'short_description' => 'Secure mobile banking app',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 1,
                'name' => 'HR Management System',
                'description' => 'A human resource management system for automating employee management tasks.',
                'short_description' => 'HR management automation',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 2,
                'name' => 'Supply Chain Optimization Software',
                'description' => 'Software to optimize supply chain management and logistics.',
                'short_description' => 'Supply chain optimization',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 3,
                'name' => 'AI-powered Chatbot',
                'description' => 'AI-based chatbot for customer support and engagement.',
                'short_description' => 'AI-powered chatbot',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 4,
                'name' => 'Data Analytics Platform',
                'description' => 'A platform to analyze large datasets and extract meaningful insights.',
                'short_description' => 'Data analytics platform',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
            [
                'company_id' => 5,
                'name' => 'Blockchain-based Security System',
                'description' => 'A security system leveraging blockchain technology for enhanced security.',
                'short_description' => 'Blockchain-based security system',
                'start_date' => $this->randomStartDate(),
                'end_date' => $this->randomEndDate(),
                'budget' => $this->randomBudget(),
            ],
        ];

        DB::table('projects')->insert($projects);

        // Job Lists
        $jobs = [
            [
                'project_id' => 1,
                'title' => 'Software Engineer',
                'minimum_salary' => 4000,
                'maximum_salary' => 7000,
                'years_of_experience' => 3,
                'skills' => ['JavaScript', 'React', 'Node.js', 'REST APIs'],
                'description' => 'Responsible for developing and maintaining scalable software applications in collaboration with cross-functional teams.',
            ],
            [
                'project_id' => 2,
                'title' => 'Full Stack Developer',
                'minimum_salary' => 5000,
                'maximum_salary' => 9000,
                'years_of_experience' => 4,
                'skills' => ['PHP', 'Laravel', 'Vue.js', 'MySQL', 'Docker'],
                'description' => 'Develop and maintain full-stack web applications with a focus on front-end and back-end integration.',
            ],
            [
                'project_id' => 3,
                'title' => 'DevOps Engineer',
                'minimum_salary' => 6000,
                'maximum_salary' => 10000,
                'years_of_experience' => 5,
                'skills' => ['AWS', 'Kubernetes', 'Jenkins', 'Terraform', 'CI/CD'],
                'description' => 'Design and maintain the CI/CD pipelines and infrastructure for scalable cloud-based applications.',
            ],
            [
                'project_id' => 4,
                'title' => 'Data Analyst',
                'minimum_salary' => 3500,
                'maximum_salary' => 6000,
                'years_of_experience' => 2,
                'skills' => ['SQL', 'Python', 'Excel', 'Data Visualization', 'Tableau'],
                'description' => 'Analyze complex datasets to provide actionable insights and support data-driven decisions for business optimization.',
            ],
            [
                'project_id' => 5,
                'title' => 'UI/UX Designer',
                'minimum_salary' => 3000,
                'maximum_salary' => 5000,
                'years_of_experience' => 2,
                'skills' => ['Figma', 'Sketch', 'Adobe XD', 'Wireframing', 'Prototyping'],
                'description' => 'Design intuitive and user-friendly interfaces for web and mobile applications, focusing on enhancing user experience.',
            ],
            [
                'project_id' => 6,
                'title' => 'Mobile Developer (iOS/Android)',
                'minimum_salary' => 4500,
                'maximum_salary' => 8000,
                'years_of_experience' => 3,
                'skills' => ['Swift', 'Kotlin', 'React Native', 'Firebase', 'Mobile App Development'],
                'description' => 'Develop high-performance mobile applications for iOS and Android platforms with a focus on usability and scalability.',
            ],
            [
                'project_id' => 7,
                'title' => 'Cloud Architect',
                'minimum_salary' => 7000,
                'maximum_salary' => 12000,
                'years_of_experience' => 6,
                'skills' => ['AWS', 'Azure', 'GCP', 'Cloud Security', 'Infrastructure Design'],
                'description' => 'Architect and design cloud solutions to ensure the scalability, reliability, and security of large-scale applications.',
            ],
            [
                'project_id' => 8,
                'title' => 'Backend Developer',
                'minimum_salary' => 4000,
                'maximum_salary' => 7000,
                'years_of_experience' => 3,
                'skills' => ['Node.js', 'Express', 'PostgreSQL', 'API Development'],
                'description' => 'Build and maintain server-side logic and database structures for web applications.',
            ],
            [
                'project_id' => 9,
                'title' => 'Project Manager',
                'minimum_salary' => 5000,
                'maximum_salary' => 9000,
                'years_of_experience' => 5,
                'skills' => ['Agile', 'Scrum', 'JIRA', 'Project Planning', 'Leadership'],
                'description' => 'Lead cross-functional teams to deliver software projects on time and within budget while managing resources and timelines.',
            ],
            [
                'project_id' => 10,
                'title' => 'Cybersecurity Specialist',
                'minimum_salary' => 5500,
                'maximum_salary' => 9500,
                'years_of_experience' => 4,
                'skills' => ['Network Security', 'Penetration Testing', 'Firewalls', 'SIEM'],
                'description' => 'Responsible for implementing and maintaining cybersecurity protocols to safeguard the company’s digital assets.',
            ],
            [
                'project_id' => 1,
                'title' => 'QA Engineer',
                'minimum_salary' => 3000,
                'maximum_salary' => 5500,
                'years_of_experience' => 2,
                'skills' => ['Automated Testing', 'Selenium', 'TestNG', 'JUnit', 'API Testing'],
                'description' => 'Develop and execute test plans to ensure the quality of software applications before release.',
            ],
            [
                'project_id' => 2,
                'title' => 'Technical Support Engineer',
                'minimum_salary' => 2500,
                'maximum_salary' => 4000,
                'years_of_experience' => 1,
                'skills' => ['Customer Support', 'Troubleshooting', 'IT Support', 'Helpdesk'],
                'description' => 'Provide technical support and troubleshooting for software products to ensure client satisfaction.',
            ],
            [
                'project_id' => 3,
                'title' => 'Business Analyst',
                'minimum_salary' => 4000,
                'maximum_salary' => 6500,
                'years_of_experience' => 3,
                'skills' => ['Business Process Modeling', 'Requirements Gathering', 'Documentation'],
                'description' => 'Analyze business processes and systems to recommend improvements and optimizations.',
            ],
            [
                'project_id' => 4,
                'title' => 'Database Administrator',
                'minimum_salary' => 4500,
                'maximum_salary' => 7500,
                'years_of_experience' => 4,
                'skills' => ['MySQL', 'PostgreSQL', 'Database Security', 'Backup and Recovery'],
                'description' => 'Manage and optimize database systems to ensure data integrity and performance.',
            ],
            [
                'project_id' => 5,
                'title' => 'Product Manager',
                'minimum_salary' => 5500,
                'maximum_salary' => 9500,
                'years_of_experience' => 5,
                'skills' => ['Product Development', 'Roadmap Planning', 'Market Research', 'UX/UI'],
                'description' => 'Define product roadmaps, gather customer requirements, and work closely with engineering teams to deliver market-ready products.',
            ],
            [
                'project_id' => 6,
                'title' => 'Machine Learning Engineer',
                'minimum_salary' => 6500,
                'maximum_salary' => 11000,
                'years_of_experience' => 5,
                'skills' => ['Python', 'TensorFlow', 'Neural Networks', 'Data Science'],
                'description' => 'Develop and deploy machine learning models for predictive analytics and AI-driven solutions.',
            ],
            [
                'project_id' => 7,
                'title' => 'System Administrator',
                'minimum_salary' => 4000,
                'maximum_salary' => 6500,
                'years_of_experience' => 3,
                'skills' => ['Linux', 'Windows Server', 'Networking', 'Virtualization', 'Cloud'],
                'description' => 'Manage the company’s IT infrastructure, including servers, networks, and cloud services.',
            ],
            [
                'project_id' => 8,
                'title' => 'AI Research Scientist',
                'minimum_salary' => 7000,
                'maximum_salary' => 12000,
                'years_of_experience' => 6,
                'skills' => ['Deep Learning', 'Reinforcement Learning', 'Research', 'Python'],
                'description' => 'Conduct cutting-edge research on artificial intelligence to develop new algorithms and AI models.',
            ],
            [
                'project_id' => 9,
                'title' => 'Technical Writer',
                'minimum_salary' => 3000,
                'maximum_salary' => 5000,
                'years_of_experience' => 2,
                'skills' => ['Technical Documentation', 'API Documentation', 'User Guides', 'Manuals'],
                'description' => 'Create clear and concise technical documentation for software products and systems.',
            ],
            [
                'project_id' => 10,
                'title' => 'IT Support Specialist',
                'minimum_salary' => 2800,
                'maximum_salary' => 4500,
                'years_of_experience' => 1,
                'skills' => ['Helpdesk', 'Troubleshooting', 'IT Support', 'Networking'],
                'description' => 'Provide first-level technical support for internal and external users, solving issues and managing IT assets.',
            ],
        ];

        $jobs = collect($jobs)->map(function ($job) {
            $job['skills'] = json_encode($job['skills']);
            return $job;
        })->toArray();

        DB::table('job_list')->insert($jobs);

        // Talents
        $talents = [
            [
                'slug' => 'john-doe',
                'name' => 'John Doe',
                'summary' => 'A skilled software developer with experience in full-stack development.',
                'job_title' => 'Software Engineer',
                'email' => 'john.doe@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 60000,
                'years_of_experience' => 4,
                'skills' => ['JavaScript', 'React', 'Node.js', 'Express'],
            ],
            [
                'slug' => 'jane-smith',
                'name' => 'Jane Smith',
                'summary' => 'Creative UI/UX designer focused on user-centered design.',
                'job_title' => 'UI/UX Designer',
                'email' => 'jane.smith@example.com',
                'phone' => '+639987654321',
                'monthly_salary' => 50000,
                'years_of_experience' => 3,
                'skills' => ['Figma', 'Sketch', 'Prototyping'],
            ],
            [
                'slug' => 'maria-garcia',
                'name' => 'Maria Garcia',
                'summary' => 'Detail-oriented data analyst with strong analytical skills.',
                'job_title' => 'Data Analyst',
                'email' => 'maria.garcia@example.com',
                'phone' => '+639876543210',
                'monthly_salary' => 55000,
                'years_of_experience' => 5,
                'skills' => ['SQL', 'Python', 'Tableau'],
            ],
            [
                'slug' => 'pedro-lopez',
                'name' => 'Pedro Lopez',
                'summary' => 'Experienced backend developer skilled in building APIs.',
                'job_title' => 'Backend Developer',
                'email' => 'pedro.lopez@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 65000,
                'years_of_experience' => 4,
                'skills' => ['Node.js', 'PHP', 'Laravel'],
            ],
            [
                'slug' => 'linda-santos',
                'name' => 'Linda Santos',
                'summary' => 'Mobile developer with expertise in Android and iOS applications.',
                'job_title' => 'Mobile Developer',
                'email' => 'linda.santos@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 70000,
                'years_of_experience' => 5,
                'skills' => ['Swift', 'Kotlin', 'React Native'],
            ],
            [
                'slug' => 'james-bond',
                'name' => 'James Bond',
                'summary' => 'Full stack developer with a passion for agile methodologies.',
                'job_title' => 'Full Stack Developer',
                'email' => 'james.bond@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 75000,
                'years_of_experience' => 6,
                'skills' => ['HTML', 'CSS', 'JavaScript', 'React'],
            ],
            [
                'slug' => 'sarah-johnson',
                'name' => 'Sarah Johnson',
                'summary' => 'Quality assurance engineer dedicated to improving product quality.',
                'job_title' => 'QA Engineer',
                'email' => 'sarah.johnson@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 48000,
                'years_of_experience' => 3,
                'skills' => ['Selenium', 'JIRA', 'Test Automation'],
            ],
            [
                'slug' => 'mike-lee',
                'name' => 'Mike Lee',
                'summary' => 'Skilled cloud architect with a focus on AWS solutions.',
                'job_title' => 'Cloud Architect',
                'email' => 'mike.lee@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 85000,
                'years_of_experience' => 8,
                'skills' => ['AWS', 'Azure', 'Cloud Security'],
            ],
            [
                'slug' => 'ella-white',
                'name' => 'Ella White',
                'summary' => 'Creative graphic designer with a strong portfolio.',
                'job_title' => 'Graphic Designer',
                'email' => 'ella.white@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 45000,
                'years_of_experience' => 2,
                'skills' => ['Photoshop', 'Illustrator', 'Branding'],
            ],
            [
                'slug' => 'alvin-brown',
                'name' => 'Alvin Brown',
                'summary' => 'Passionate data scientist specializing in machine learning.',
                'job_title' => 'Data Scientist',
                'email' => 'alvin.brown@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 90000,
                'years_of_experience' => 5,
                'skills' => ['Machine Learning', 'R', 'Python'],
            ],
            // Add more talents to reach 100
            [
                'slug' => 'carmen-rodriguez',
                'name' => 'Carmen Rodriguez',
                'summary' => 'Motivated project manager with a proven track record of successful projects.',
                'job_title' => 'Project Manager',
                'email' => 'carmen.rodriguez@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 78000,
                'years_of_experience' => 7,
                'skills' => ['Agile', 'Scrum', 'Leadership'],
            ],
            [
                'slug' => 'andre-martinez',
                'name' => 'Andre Martinez',
                'summary' => 'Junior software developer eager to learn and grow in the field.',
                'job_title' => 'Junior Developer',
                'email' => 'andre.martinez@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 30000,
                'years_of_experience' => 1,
                'skills' => ['Java', 'HTML', 'CSS'],
            ],
            [
                'slug' => 'clara-perez',
                'name' => 'Clara Perez',
                'summary' => 'Highly organized administrative assistant with strong multitasking skills.',
                'job_title' => 'Administrative Assistant',
                'email' => 'clara.perez@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 35000,
                'years_of_experience' => 2,
                'skills' => ['Microsoft Office', 'Scheduling', 'Communication'],
            ],
            [
                'slug' => 'roberto-martinez',
                'name' => 'Roberto Martinez',
                'summary' => 'IT support specialist with a knack for troubleshooting.',
                'job_title' => 'IT Support Specialist',
                'email' => 'roberto.martinez@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 40000,
                'years_of_experience' => 3,
                'skills' => ['Troubleshooting', 'Network Configuration', 'Customer Service'],
            ],
            [
                'slug' => 'zara-james',
                'name' => 'Zara James',
                'summary' => 'E-commerce manager skilled in online retail strategies.',
                'job_title' => 'E-commerce Manager',
                'email' => 'zara.james@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 72000,
                'years_of_experience' => 5,
                'skills' => ['SEO', 'Digital Marketing', 'Analytics'],
            ],
            [
                'slug' => 'benedict-chua',
                'name' => 'Benedict Chua',
                'summary' => 'Systems analyst with a focus on business process improvement.',
                'job_title' => 'Systems Analyst',
                'email' => 'benedict.chua@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 60000,
                'years_of_experience' => 4,
                'skills' => ['Business Analysis', 'SQL', 'Documentation'],
            ],
            [
                'slug' => 'patricia-castro',
                'name' => 'Patricia Castro',
                'summary' => 'Graphic designer with expertise in visual branding.',
                'job_title' => 'Graphic Designer',
                'email' => 'patricia.castro@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 48000,
                'years_of_experience' => 2,
                'skills' => ['Photoshop', 'InDesign', 'Creativity'],
            ],
            [
                'slug' => 'henry-zhang',
                'name' => 'Henry Zhang',
                'summary' => 'Blockchain developer with experience in smart contracts.',
                'job_title' => 'Blockchain Developer',
                'email' => 'henry.zhang@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 95000,
                'years_of_experience' => 6,
                'skills' => ['Solidity', 'Ethereum', 'Cryptography'],
            ],
            [
                'slug' => 'sofia-jones',
                'name' => 'Sofia Jones',
                'summary' => 'Marketing specialist with a focus on content strategy.',
                'job_title' => 'Marketing Specialist',
                'email' => 'sofia.jones@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 52000,
                'years_of_experience' => 3,
                'skills' => ['Content Creation', 'SEO', 'Social Media'],
            ],
            [
                'slug' => 'ivan-hernandez',
                'name' => 'Ivan Hernandez',
                'summary' => 'Network engineer with experience in cybersecurity.',
                'job_title' => 'Network Engineer',
                'email' => 'ivan.hernandez@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 73000,
                'years_of_experience' => 5,
                'skills' => ['Network Security', 'Cisco', 'Firewalls'],
            ],
            [
                'slug' => 'sharon-davis',
                'name' => 'Sharon Davis',
                'summary' => 'Data engineer specializing in ETL processes.',
                'job_title' => 'Data Engineer',
                'email' => 'sharon.davis@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 80000,
                'years_of_experience' => 4,
                'skills' => ['ETL', 'Python', 'Big Data'],
            ],
            [
                'slug' => 'nikki-evans',
                'name' => 'Nikki Evans',
                'summary' => 'Salesforce developer focused on CRM solutions.',
                'job_title' => 'Salesforce Developer',
                'email' => 'nikki.evans@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 67000,
                'years_of_experience' => 4,
                'skills' => ['Salesforce', 'CRM', 'Apex'],
            ],
            [
                'slug' => 'andre-kumar',
                'name' => 'Andre Kumar',
                'summary' => 'Front-end developer with a passion for responsive design.',
                'job_title' => 'Front-end Developer',
                'email' => 'andre.kumar@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 55000,
                'years_of_experience' => 3,
                'skills' => ['HTML', 'CSS', 'JavaScript'],
            ],
            [
                'slug' => 'clara-mills',
                'name' => 'Clara Mills',
                'summary' => 'Project coordinator skilled in managing timelines and deliverables.',
                'job_title' => 'Project Coordinator',
                'email' => 'clara.mills@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 42000,
                'years_of_experience' => 2,
                'skills' => ['Time Management', 'Organization', 'Communication'],
            ],
            [
                'slug' => 'harry-lee',
                'name' => 'Harry Lee',
                'summary' => 'Database administrator with a strong focus on performance tuning.',
                'job_title' => 'Database Administrator',
                'email' => 'harry.lee@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 68000,
                'years_of_experience' => 5,
                'skills' => ['MySQL', 'PostgreSQL', 'Tuning'],
            ],
            [
                'slug' => 'jessica-king',
                'name' => 'Jessica King',
                'summary' => 'SEO specialist with a proven record of improving search rankings.',
                'job_title' => 'SEO Specialist',
                'email' => 'jessica.king@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 48000,
                'years_of_experience' => 3,
                'skills' => ['SEO', 'Google Analytics', 'Keyword Research'],
            ],
            [
                'slug' => 'omar-gonzalez',
                'name' => 'Omar Gonzalez',
                'summary' => 'Information security analyst dedicated to protecting company data.',
                'job_title' => 'Information Security Analyst',
                'email' => 'omar.gonzalez@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 85000,
                'years_of_experience' => 6,
                'skills' => ['Information Security', 'Risk Assessment', 'Compliance'],
            ],
            [
                'slug' => 'leo-salas',
                'name' => 'Leo Salas',
                'summary' => 'Business analyst with experience in requirement gathering.',
                'job_title' => 'Business Analyst',
                'email' => 'leo.salas@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 59000,
                'years_of_experience' => 4,
                'skills' => ['Business Analysis', 'Stakeholder Management', 'Documentation'],
            ],
            [
                'slug' => 'ivan-cordova',
                'name' => 'Ivan Cordova',
                'summary' => 'Technical writer with experience in creating documentation for software products.',
                'job_title' => 'Technical Writer',
                'email' => 'ivan.cordova@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 46000,
                'years_of_experience' => 2,
                'skills' => ['Technical Writing', 'Documentation', 'Editing'],
            ],
            [
                'slug' => 'flora-shaw',
                'name' => 'Flora Shaw',
                'summary' => 'Software tester focused on functional and performance testing.',
                'job_title' => 'Software Tester',
                'email' => 'flora.shaw@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 47000,
                'years_of_experience' => 2,
                'skills' => ['Functional Testing', 'Automation Testing', 'Bug Tracking'],
            ],
            [
                'slug' => 'rafael-nieto',
                'name' => 'Rafael Nieto',
                'summary' => 'Experienced web developer skilled in PHP and Laravel.',
                'job_title' => 'Web Developer',
                'email' => 'rafael.nieto@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 62000,
                'years_of_experience' => 5,
                'skills' => ['PHP', 'Laravel', 'HTML'],
            ],
            [
                'slug' => 'shira-yamamoto',
                'name' => 'Shira Yamamoto',
                'summary' => 'Frontend engineer specializing in JavaScript frameworks.',
                'job_title' => 'Frontend Engineer',
                'email' => 'shira.yamamoto@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 60000,
                'years_of_experience' => 3,
                'skills' => ['React', 'Vue.js', 'TypeScript'],
            ],
            [
                'slug' => 'matteo-rossi',
                'name' => 'Matteo Rossi',
                'summary' => 'Senior developer with expertise in cloud computing.',
                'job_title' => 'Senior Developer',
                'email' => 'matteo.rossi@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 85000,
                'years_of_experience' => 7,
                'skills' => ['AWS', 'Azure', 'Docker'],
            ],
            [
                'slug' => 'elena-kovaleva',
                'name' => 'Elena Kovaleva',
                'summary' => 'Mobile application developer with experience in cross-platform solutions.',
                'job_title' => 'Mobile App Developer',
                'email' => 'elena.kovaleva@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 72000,
                'years_of_experience' => 5,
                'skills' => ['Flutter', 'React Native', 'JavaScript'],
            ],
            [
                'slug' => 'george-king',
                'name' => 'George King',
                'summary' => 'IT consultant with a strong background in system integrations.',
                'job_title' => 'IT Consultant',
                'email' => 'george.king@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 79000,
                'years_of_experience' => 6,
                'skills' => ['System Integration', 'Consulting', 'IT Strategy'],
            ],
            [
                'slug' => 'sonia-harrison',
                'name' => 'Sonia Harrison',
                'summary' => 'Digital marketing strategist with a focus on social media campaigns.',
                'job_title' => 'Digital Marketing Strategist',
                'email' => 'sonia.harrison@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 56000,
                'years_of_experience' => 4,
                'skills' => ['Social Media', 'Content Strategy', 'Analytics'],
            ],
            [
                'slug' => 'vincent-ma',
                'name' => 'Vincent Ma',
                'summary' => 'Product manager with experience in agile methodologies.',
                'job_title' => 'Product Manager',
                'email' => 'vincent.ma@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 78000,
                'years_of_experience' => 5,
                'skills' => ['Agile', 'Scrum', 'Product Development'],
            ],
            [
                'slug' => 'megan-jackson',
                'name' => 'Megan Jackson',
                'summary' => 'Data analyst specializing in data visualization.',
                'job_title' => 'Data Analyst',
                'email' => 'megan.jackson@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 49000,
                'years_of_experience' => 3,
                'skills' => ['Data Visualization', 'SQL', 'Python'],
            ],
            [
                'slug' => 'nathan-lee',
                'name' => 'Nathan Lee',
                'summary' => 'Systems administrator with experience in cloud services.',
                'job_title' => 'Systems Administrator',
                'email' => 'nathan.lee@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 62000,
                'years_of_experience' => 4,
                'skills' => ['Cloud Services', 'Windows Server', 'Linux'],
            ],
            [
                'slug' => 'samantha-adams',
                'name' => 'Samantha Adams',
                'summary' => 'UX/UI designer focusing on user-centered design.',
                'job_title' => 'UX/UI Designer',
                'email' => 'samantha.adams@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 55000,
                'years_of_experience' => 4,
                'skills' => ['User Research', 'Wireframing', 'Prototyping'],
            ],
            [
                'slug' => 'kevin-park',
                'name' => 'Kevin Park',
                'summary' => 'Content writer with a knack for storytelling.',
                'job_title' => 'Content Writer',
                'email' => 'kevin.park@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 43000,
                'years_of_experience' => 2,
                'skills' => ['Writing', 'Editing', 'Storytelling'],
            ],
            [
                'slug' => 'nicole-rodriguez',
                'name' => 'Nicole Rodriguez',
                'summary' => 'Cloud solutions architect with a focus on AWS.',
                'job_title' => 'Cloud Solutions Architect',
                'email' => 'nicole.rodriguez@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 88000,
                'years_of_experience' => 6,
                'skills' => ['AWS', 'Cloud Architecture', 'Infrastructure'],
            ],
            [
                'slug' => 'jack-martin',
                'name' => 'Jack Martin',
                'summary' => 'Graphic designer with experience in branding and identity.',
                'job_title' => 'Graphic Designer',
                'email' => 'jack.martin@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 47000,
                'years_of_experience' => 3,
                'skills' => ['Branding', 'Adobe Creative Suite', 'Illustration'],
            ],
            [
                'slug' => 'zoe-huang',
                'name' => 'Zoe Huang',
                'summary' => 'Operations manager with a focus on process optimization.',
                'job_title' => 'Operations Manager',
                'email' => 'zoe.huang@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 72000,
                'years_of_experience' => 5,
                'skills' => ['Process Optimization', 'Team Management', 'Logistics'],
            ],
            [
                'slug' => 'andy-wang',
                'name' => 'Andy Wang',
                'summary' => 'Financial analyst with expertise in budgeting and forecasting.',
                'job_title' => 'Financial Analyst',
                'email' => 'andy.wang@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 61000,
                'years_of_experience' => 4,
                'skills' => ['Budgeting', 'Forecasting', 'Financial Modeling'],
            ],
            [
                'slug' => 'briana-lopez',
                'name' => 'Briana Lopez',
                'summary' => 'HR specialist with a focus on recruitment and talent acquisition.',
                'job_title' => 'HR Specialist',
                'email' => 'briana.lopez@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 54000,
                'years_of_experience' => 4,
                'skills' => ['Recruitment', 'Interviewing', 'Talent Acquisition'],
            ],
            [
                'slug' => 'ryan-gonzalez',
                'name' => 'Ryan Gonzalez',
                'summary' => 'E-commerce manager with experience in online retail.',
                'job_title' => 'E-commerce Manager',
                'email' => 'ryan.gonzalez@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 60000,
                'years_of_experience' => 4,
                'skills' => ['E-commerce', 'Digital Marketing', 'Analytics'],
            ],
            [
                'slug' => 'lila-chen',
                'name' => 'Lila Chen',
                'summary' => 'Social media manager with expertise in audience engagement.',
                'job_title' => 'Social Media Manager',
                'email' => 'lila.chen@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 52000,
                'years_of_experience' => 3,
                'skills' => ['Social Media', 'Content Creation', 'Community Management'],
            ],
            [
                'slug' => 'rafael-garcia',
                'name' => 'Rafael Garcia',
                'summary' => 'Systems analyst with experience in requirements gathering.',
                'job_title' => 'Systems Analyst',
                'email' => 'rafael.garcia@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 70000,
                'years_of_experience' => 5,
                'skills' => ['Requirements Gathering', 'Analysis', 'Documentation'],
            ],
            [
                'slug' => 'grace-brown',
                'name' => 'Grace Brown',
                'summary' => 'Mobile UX designer with a focus on user experience.',
                'job_title' => 'Mobile UX Designer',
                'email' => 'grace.brown@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 57000,
                'years_of_experience' => 3,
                'skills' => ['User Experience', 'Mobile Design', 'Prototyping'],
            ],
            [
                'slug' => 'james-miller',
                'name' => 'James Miller',
                'summary' => 'SEO analyst with a background in analytics and optimization.',
                'job_title' => 'SEO Analyst',
                'email' => 'james.miller@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 48000,
                'years_of_experience' => 3,
                'skills' => ['SEO', 'Data Analysis', 'Keyword Research'],
            ],
            [
                'slug' => 'evan-kim',
                'name' => 'Evan Kim',
                'summary' => 'Business development manager focused on strategic partnerships.',
                'job_title' => 'Business Development Manager',
                'email' => 'evan.kim@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 72000,
                'years_of_experience' => 5,
                'skills' => ['Business Development', 'Partnerships', 'Negotiation'],
            ],
            [
                'slug' => 'selena-park',
                'name' => 'Selena Park',
                'summary' => 'Quality assurance engineer with a focus on test automation.',
                'job_title' => 'Quality Assurance Engineer',
                'email' => 'selena.park@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 51000,
                'years_of_experience' => 3,
                'skills' => ['Test Automation', 'Quality Assurance', 'Testing'],
            ],
            [
                'slug' => 'victor-nguyen',
                'name' => 'Victor Nguyen',
                'summary' => 'Software architect with expertise in microservices architecture.',
                'job_title' => 'Software Architect',
                'email' => 'victor.nguyen@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 90000,
                'years_of_experience' => 7,
                'skills' => ['Microservices', 'Architecture', 'Design Patterns'],
            ],
            [
                'slug' => 'isabella-martinez',
                'name' => 'Isabella Martinez',
                'summary' => 'Customer success manager focused on client satisfaction.',
                'job_title' => 'Customer Success Manager',
                'email' => 'isabella.martinez@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 68000,
                'years_of_experience' => 4,
                'skills' => ['Client Relationship', 'Customer Support', 'Retention'],
            ],
            [
                'slug' => 'peter-sullivan',
                'name' => 'Peter Sullivan',
                'summary' => 'Data scientist with a focus on machine learning.',
                'job_title' => 'Data Scientist',
                'email' => 'peter.sullivan@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 95000,
                'years_of_experience' => 8,
                'skills' => ['Machine Learning', 'Data Analysis', 'Python'],
            ],
            [
                'slug' => 'zoey-brown',
                'name' => 'Zoey Brown',
                'summary' => 'Digital content creator specializing in video production.',
                'job_title' => 'Digital Content Creator',
                'email' => 'zoey.brown@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 52000,
                'years_of_experience' => 3,
                'skills' => ['Video Production', 'Content Creation', 'Social Media'],
            ],
            [
                'slug' => 'timothy-evans',
                'name' => 'Timothy Evans',
                'summary' => 'User experience researcher focused on usability testing.',
                'job_title' => 'User Experience Researcher',
                'email' => 'timothy.evans@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 62000,
                'years_of_experience' => 4,
                'skills' => ['Usability Testing', 'User Research', 'Interviews'],
            ],
            [
                'slug' => 'anita-patel',
                'name' => 'Anita Patel',
                'summary' => 'Product designer specializing in user-centered design.',
                'job_title' => 'Product Designer',
                'email' => 'anita.patel@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 58000,
                'years_of_experience' => 3,
                'skills' => ['User-Centered Design', 'Prototyping', 'Wireframing'],
            ],
            [
                'slug' => 'dylan-shepherd',
                'name' => 'Dylan Shepherd',
                'summary' => 'Technical support specialist with a focus on customer service.',
                'job_title' => 'Technical Support Specialist',
                'email' => 'dylan.shepherd@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 49000,
                'years_of_experience' => 3,
                'skills' => ['Customer Service', 'Technical Support', 'Troubleshooting'],
            ],
            [
                'slug' => 'laura-sanchez',
                'name' => 'Laura Sanchez',
                'summary' => 'Web designer with experience in responsive design.',
                'job_title' => 'Web Designer',
                'email' => 'laura.sanchez@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 55000,
                'years_of_experience' => 3,
                'skills' => ['Responsive Design', 'HTML', 'CSS'],
            ],
            [
                'slug' => 'elijah-turner',
                'name' => 'Elijah Turner',
                'summary' => 'Social media strategist with a passion for community building.',
                'job_title' => 'Social Media Strategist',
                'email' => 'elijah.turner@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 52000,
                'years_of_experience' => 3,
                'skills' => ['Community Building', 'Content Creation', 'Social Media'],
            ],
            [
                'slug' => 'madeline-brown',
                'name' => 'Madeline Brown',
                'summary' => 'Data entry specialist with a focus on accuracy and efficiency.',
                'job_title' => 'Data Entry Specialist',
                'email' => 'madeline.brown@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 41000,
                'years_of_experience' => 2,
                'skills' => ['Data Entry', 'Accuracy', 'Efficiency'],
            ],
            [
                'slug' => 'derek-cole',
                'name' => 'Derek Cole',
                'summary' => 'Product marketing manager focused on brand awareness.',
                'job_title' => 'Product Marketing Manager',
                'email' => 'derek.cole@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 68000,
                'years_of_experience' => 5,
                'skills' => ['Product Marketing', 'Brand Awareness', 'Market Research'],
            ],
            [
                'slug' => 'kylie-harrison',
                'name' => 'Kylie Harrison',
                'summary' => 'Financial controller with expertise in financial reporting.',
                'job_title' => 'Financial Controller',
                'email' => 'kylie.harrison@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 75000,
                'years_of_experience' => 5,
                'skills' => ['Financial Reporting', 'Budgeting', 'Analysis'],
            ],
            [
                'slug' => 'charles-taylor',
                'name' => 'Charles Taylor',
                'summary' => 'Software engineer specializing in backend development.',
                'job_title' => 'Software Engineer',
                'email' => 'charles.taylor@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 70000,
                'years_of_experience' => 5,
                'skills' => ['Backend Development', 'Java', 'Spring'],
            ],
            [
                'slug' => 'vivian-lopez',
                'name' => 'Vivian Lopez',
                'summary' => 'Human resources manager focused on employee engagement.',
                'job_title' => 'Human Resources Manager',
                'email' => 'vivian.lopez@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 80000,
                'years_of_experience' => 6,
                'skills' => ['Employee Engagement', 'Recruitment', 'Training'],
            ],
            [
                'slug' => 'giovanni-vargas',
                'name' => 'Giovanni Vargas',
                'summary' => 'Cloud security specialist with a focus on AWS.',
                'job_title' => 'Cloud Security Specialist',
                'email' => 'giovanni.vargas@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 91000,
                'years_of_experience' => 7,
                'skills' => ['Cloud Security', 'AWS', 'Network Security'],
            ],
            [
                'slug' => 'lara-evans',
                'name' => 'Lara Evans',
                'summary' => 'Brand manager with a strong background in digital marketing.',
                'job_title' => 'Brand Manager',
                'email' => 'lara.evans@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 60000,
                'years_of_experience' => 4,
                'skills' => ['Brand Management', 'Digital Marketing', 'SEO'],
            ],
            [
                'slug' => 'benjamin-thomas',
                'name' => 'Benjamin Thomas',
                'summary' => 'Information systems manager with a focus on project management.',
                'job_title' => 'Information Systems Manager',
                'email' => 'benjamin.thomas@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 88000,
                'years_of_experience' => 6,
                'skills' => ['Project Management', 'Information Systems', 'Team Leadership'],
            ],
            [
                'slug' => 'diana-carter',
                'name' => 'Diana Carter',
                'summary' => 'Digital product manager specializing in mobile applications.',
                'job_title' => 'Digital Product Manager',
                'email' => 'diana.carter@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 75000,
                'years_of_experience' => 5,
                'skills' => ['Product Management', 'Mobile Applications', 'Agile'],
            ],
            [
                'slug' => 'julia-garcia',
                'name' => 'Julia Garcia',
                'summary' => 'Software quality analyst focused on automated testing.',
                'job_title' => 'Software Quality Analyst',
                'email' => 'julia.garcia@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 58000,
                'years_of_experience' => 4,
                'skills' => ['Automated Testing', 'Quality Assurance', 'Test Management'],
            ],
            [
                'slug' => 'nora-wright',
                'name' => 'Nora Wright',
                'summary' => 'Corporate trainer with experience in employee development.',
                'job_title' => 'Corporate Trainer',
                'email' => 'nora.wright@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 64000,
                'years_of_experience' => 4,
                'skills' => ['Training', 'Employee Development', 'Facilitation'],
            ],
            [
                'slug' => 'lucas-klein',
                'name' => 'Lucas Klein',
                'summary' => 'Market research analyst with a focus on consumer behavior.',
                'job_title' => 'Market Research Analyst',
                'email' => 'lucas.klein@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 57000,
                'years_of_experience' => 3,
                'skills' => ['Market Research', 'Data Analysis', 'Consumer Behavior'],
            ],
            [
                'slug' => 'marissa-jones',
                'name' => 'Marissa Jones',
                'summary' => 'Database administrator with a focus on performance tuning.',
                'job_title' => 'Database Administrator',
                'email' => 'marissa.jones@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 69000,
                'years_of_experience' => 5,
                'skills' => ['Database Management', 'Performance Tuning', 'SQL'],
            ],
            [
                'slug' => 'harryz-lee',
                'name' => 'Harryz Lee',
                'summary' => 'Sales executive with a focus on B2B sales.',
                'job_title' => 'Sales Executive',
                'email' => 'harryz.lee@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 64000,
                'years_of_experience' => 4,
                'skills' => ['B2B Sales', 'Negotiation', 'Lead Generation'],
            ],
            [
                'slug' => 'sophia-miller',
                'name' => 'Sophia Miller',
                'summary' => 'Virtual assistant with expertise in administrative tasks.',
                'job_title' => 'Virtual Assistant',
                'email' => 'sophia.miller@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 42000,
                'years_of_experience' => 2,
                'skills' => ['Administrative Tasks', 'Organization', 'Communication'],
            ],
            [
                'slug' => 'andrew-wang',
                'name' => 'Andrew Wang',
                'summary' => 'Business analyst with expertise in data analytics.',
                'job_title' => 'Business Analyst',
                'email' => 'andrew.wang@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 70000,
                'years_of_experience' => 4,
                'skills' => ['Data Analytics', 'Requirements Gathering', 'Documentation'],
            ],
            [
                'slug' => 'isabella-rodriguez',
                'name' => 'Isabella Rodriguez',
                'summary' => 'Web developer with a focus on front-end technologies.',
                'job_title' => 'Web Developer',
                'email' => 'isabella.rodriguez@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 62000,
                'years_of_experience' => 4,
                'skills' => ['HTML', 'CSS', 'JavaScript'],
            ],
            [
                'slug' => 'cameron-hall',
                'name' => 'Cameron Hall',
                'summary' => 'IT project manager with experience in software development.',
                'job_title' => 'IT Project Manager',
                'email' => 'cameron.hall@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 76000,
                'years_of_experience' => 5,
                'skills' => ['Project Management', 'Software Development', 'Agile'],
            ],
            [
                'slug' => 'grace-martin',
                'name' => 'Grace Martin',
                'summary' => 'Blockchain developer with experience in Ethereum.',
                'job_title' => 'Blockchain Developer',
                'email' => 'grace.martin@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 85000,
                'years_of_experience' => 6,
                'skills' => ['Blockchain', 'Ethereum', 'Smart Contracts'],
            ],
            [
                'slug' => 'ryan-smith',
                'name' => 'Ryan Smith',
                'summary' => 'SEO specialist with a focus on on-page optimization.',
                'job_title' => 'SEO Specialist',
                'email' => 'ryan.smith@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 50000,
                'years_of_experience' => 3,
                'skills' => ['SEO', 'On-Page Optimization', 'Content Strategy'],
            ],
            [
                'slug' => 'amelia-lee',
                'name' => 'Amelia Lee',
                'summary' => 'Graphic designer focused on web design and branding.',
                'job_title' => 'Graphic Designer',
                'email' => 'amelia.lee@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 49000,
                'years_of_experience' => 2,
                'skills' => ['Web Design', 'Branding', 'Adobe Creative Suite'],
            ],
            [
                'slug' => 'harper-miller',
                'name' => 'Harper Miller',
                'summary' => 'Customer support representative with a passion for helping others.',
                'job_title' => 'Customer Support Representative',
                'email' => 'harper.miller@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 40000,
                'years_of_experience' => 2,
                'skills' => ['Customer Support', 'Problem Solving', 'Communication'],
            ],
            [
                'slug' => 'zoe-smith',
                'name' => 'Zoe Smith',
                'summary' => 'Content strategist with a background in digital marketing.',
                'job_title' => 'Content Strategist',
                'email' => 'zoe.smith@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 56000,
                'years_of_experience' => 4,
                'skills' => ['Content Strategy', 'Digital Marketing', 'SEO'],
            ],
            [
                'slug' => 'cynthia-adams',
                'name' => 'Cynthia Adams',
                'summary' => 'Digital marketing manager with experience in social media marketing.',
                'job_title' => 'Digital Marketing Manager',
                'email' => 'cynthia.adams@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 75000,
                'years_of_experience' => 5,
                'skills' => ['Social Media Marketing', 'Content Marketing', 'Analytics'],
            ],
            [
                'slug' => 'landon-thomas',
                'name' => 'Landon Thomas',
                'summary' => 'Technical writer with a focus on software documentation.',
                'job_title' => 'Technical Writer',
                'email' => 'landon.thomas@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 52000,
                'years_of_experience' => 3,
                'skills' => ['Technical Writing', 'Documentation', 'Editing'],
            ],
            [
                'slug' => 'addison-jones',
                'name' => 'Addison Jones',
                'summary' => 'Operations analyst with experience in process improvement.',
                'job_title' => 'Operations Analyst',
                'email' => 'addison.jones@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 65000,
                'years_of_experience' => 4,
                'skills' => ['Process Improvement', 'Data Analysis', 'Reporting'],
            ],
            [
                'slug' => 'samantha-lee',
                'name' => 'Samantha Lee',
                'summary' => 'Business intelligence analyst focused on data visualization.',
                'job_title' => 'Business Intelligence Analyst',
                'email' => 'samantha.lee@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 71000,
                'years_of_experience' => 4,
                'skills' => ['Data Visualization', 'Business Intelligence', 'Reporting'],
            ],
            [
                'slug' => 'william-wilson',
                'name' => 'William Wilson',
                'summary' => 'Cybersecurity analyst with expertise in threat assessment.',
                'job_title' => 'Cybersecurity Analyst',
                'email' => 'william.wilson@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 90000,
                'years_of_experience' => 6,
                'skills' => ['Cybersecurity', 'Threat Assessment', 'Incident Response'],
            ],
            [
                'slug' => 'olivia-harris',
                'name' => 'Olivia Harris',
                'summary' => 'Frontend developer with experience in React and Angular.',
                'job_title' => 'Frontend Developer',
                'email' => 'olivia.harris@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 62000,
                'years_of_experience' => 4,
                'skills' => ['React', 'Angular', 'HTML'],
            ],
            [
                'slug' => 'liam-james',
                'name' => 'Liam James',
                'summary' => 'SEO analyst with a focus on technical SEO.',
                'job_title' => 'SEO Analyst',
                'email' => 'liam.james@example.com',
                'phone' => '+639012345678',
                'monthly_salary' => 55000,
                'years_of_experience' => 4,
                'skills' => ['Technical SEO', 'SEO Audits', 'Analytics'],
            ],
            [
                'slug' => 'ava-white',
                'name' => 'Ava White',
                'summary' => 'Cloud engineer with a focus on infrastructure management.',
                'job_title' => 'Cloud Engineer',
                'email' => 'ava.white@example.com',
                'phone' => '+639123456789',
                'monthly_salary' => 88000,
                'years_of_experience' => 5,
                'skills' => ['Cloud Infrastructure', 'AWS', 'DevOps'],
            ],
            [
                'slug' => 'chris-anderson',
                'name' => 'Chris Anderson',
                'summary' => 'Project coordinator with a background in construction.',
                'job_title' => 'Project Coordinator',
                'email' => 'chris.anderson@example.com',
                'phone' => '+639234567890',
                'monthly_salary' => 58000,
                'years_of_experience' => 3,
                'skills' => ['Project Coordination', 'Construction Management', 'Scheduling'],
            ],
            [
                'slug' => 'nina-james',
                'name' => 'Nina James',
                'summary' => 'Quality assurance engineer with a focus on automated testing.',
                'job_title' => 'Quality Assurance Engineer',
                'email' => 'nina.james@example.com',
                'phone' => '+639345678901',
                'monthly_salary' => 59000,
                'years_of_experience' => 3,
                'skills' => ['Automated Testing', 'Quality Assurance', 'Debugging'],
            ],
            [
                'slug' => 'isabella-gonzalez',
                'name' => 'Isabella Gonzalez',
                'summary' => 'Research analyst focused on market trends.',
                'job_title' => 'Research Analyst',
                'email' => 'isabella.gonzalez@example.com',
                'phone' => '+639456789012',
                'monthly_salary' => 51000,
                'years_of_experience' => 3,
                'skills' => ['Market Research', 'Data Analysis', 'Reporting'],
            ],
            [
                'slug' => 'gavin-brown',
                'name' => 'Gavin Brown',
                'summary' => 'Logistics manager with experience in supply chain management.',
                'job_title' => 'Logistics Manager',
                'email' => 'gavin.brown@example.com',
                'phone' => '+639567890123',
                'monthly_salary' => 72000,
                'years_of_experience' => 6,
                'skills' => ['Supply Chain Management', 'Logistics', 'Operations'],
            ],
            [
                'slug' => 'maya-martinez',
                'name' => 'Maya Martinez',
                'summary' => 'Digital marketing strategist with a focus on PPC campaigns.',
                'job_title' => 'Digital Marketing Strategist',
                'email' => 'maya.martinez@example.com',
                'phone' => '+639678901234',
                'monthly_salary' => 64000,
                'years_of_experience' => 4,
                'skills' => ['PPC Campaigns', 'Digital Marketing', 'Analytics'],
            ],
            [
                'slug' => 'isaac-lewis',
                'name' => 'Isaac Lewis',
                'summary' => 'Sales manager with expertise in team leadership.',
                'job_title' => 'Sales Manager',
                'email' => 'isaac.lewis@example.com',
                'phone' => '+639789012345',
                'monthly_salary' => 83000,
                'years_of_experience' => 7,
                'skills' => ['Sales Management', 'Team Leadership', 'B2B Sales'],
            ],
            [
                'slug' => 'penelope-scott',
                'name' => 'Penelope Scott',
                'summary' => 'Copywriter focused on brand storytelling.',
                'job_title' => 'Copywriter',
                'email' => 'penelope.scott@example.com',
                'phone' => '+639890123456',
                'monthly_salary' => 57000,
                'years_of_experience' => 4,
                'skills' => ['Copywriting', 'Brand Storytelling', 'Content Creation'],
            ],
            [
                'slug' => 'xavier-harris',
                'name' => 'Xavier Harris',
                'summary' => 'DevOps engineer with a focus on continuous integration.',
                'job_title' => 'DevOps Engineer',
                'email' => 'xavier.harris@example.com',
                'phone' => '+639901234567',
                'monthly_salary' => 90000,
                'years_of_experience' => 5,
                'skills' => ['DevOps', 'Continuous Integration', 'Cloud Computing'],
            ],
        ];

        $talents = collect($talents)->map(function ($talent) {
            $talent['skills'] = json_encode($talent['skills']);
            return $talent;
        })->toArray();

        DB::table('talent')->insert($talents);
    }

    /**
     * Generate a random start date between October 25 and December 25.
     */
    private function randomStartDate()
    {
        $start = Carbon::createFromDate(2024, 10, 25);
        $end = Carbon::createFromDate(2024, 12, 25);
        return Carbon::createFromTimestamp(rand($start->timestamp, $end->timestamp))->toDateString();
    }

    /**
     * Generate a random end date X months from the start date (between 1 to 12 months).
     */
    private function randomEndDate()
    {
        $months = rand(1, 12); // Random duration between 1 and 12 months
        return Carbon::now()->addMonths($months)->toDateString();
    }

    /**
     * Generate a random budget between 50,000 and 500,000 USD.
     */
    private function randomBudget()
    {
        return rand(50000, 500000); // Random budget in USD
    }
}
